### ISSUE TITLE
Cannot make: lib maxent lacks libmaxent.a(modelfile.o)

### ISSUE THREAD

**Issue by ConnieTong** [lzhang10/maxent#12]
When I followed INSTALL instructions, in the make phase, the build process aborted because lack of libmaxent.a. What could be the problem? Is there any thrid-party lib I need to install? Thanks.

**Comment by baimin1** [comment]
**info** configure will use boost lib shipped with this package
and then make fail ,how can i do details

**Comment by lzhang10** [comment]
Can you be more specific of the OS you were building under? I just built the latest code under Ubuntu 15.04 64bit from scratch using the shipped boost and everything is fine.

**Comment by lzhang10** [comment]
Ok. I can replicate your error using system boost lib. I've pushed a fix. #12
