### ISSUE TITLE
Inconsistent, but comparable results

### ISSUE THREAD

**Issue by zhang-jian** [lzhang10/maxent#13]
Hi,

First, thanks for this great toolkit.
Second, this is a question rather than an issue.

I used the python binding version in my experiment. I run the same training code 3 times, but the features file is shuffled at each run.

During 3 runs, I can see the same prints (except the logged time):
2015-09-07 23:00:00,343 : INFO : Start training:
2015-09-07 23:00:11,437 : INFO : Conditional Maximum Entropy Model (C++ version)
Number of context predicates  : 79868
Number of outcome             : 9
Number of paramaters(features): 120163

My model is trained with
        m = cmaxent.MaxentModel()
        m.begin_add_event()
        c = 0
        for line in open(self.train_feature_file):
            line = line.strip()
            f = line.split("\t")[1].split()
            t = str(line.split("\t")[0])
            m.add_event(f, t)
            c += 1
        m.end_add_event()
        m.train(100, 'lbfgs', 0.0, 1E-05)
        logging.info(m)
        m.save(self.model_file)

When predicting, I am using something like,
        features = [f.encode("utf-8") for f in features]
         pred_tag = m.predict(features)
         pred_tags[idx] = pred_tag

However, I am getting different accuracies each time:
0.987249761678
0.987408643152
0.987170320941

The results are comparable, but different.

So, is this behavior expected? and why?

Thanks

J

**Comment by lzhang10** [comment]
If the input is the same the model file should be the same. You can dump the model as txt file and see if they are the same across 3 runs. If the model files are the same but you get different result during prediction, you need to double check if you are testing on the same input (after shuffling).
