### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by luuik** [lzhang10/maxent#14]
Hi

I seem to have inconsistent results when using the lib on multiple threads (calling maxentmodel::eval).
Then I see in the Jamrules : -DBOOST_DISABLE_THREADS ; # no need to link pthread lib

What does it mean? Is the lib (or ate least maxentmodel::eval) supporting multithread or not?

Thanks a lot,

Loic

**Comment by lzhang10** [comment]
The toolkit does not use multi-threading. The flag in the Jamrules is to ensure we don't have any dependence on threading libraries.
